name: Publish Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major
          - keep

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies # vsce etc
        run: | # shell
          npm i @vscode/vsce -g

      - name: Setup Github Actions # allow use of `git push`
        run: | # shell
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync Github Actions"

      - name: Package Extension # `.vsix` file
        run: | # shell
          if [ ${{ github.event.inputs.version }} = "keep" ]; then
            vsce package
          else
            vsce package ${{ github.event.inputs.version }}
          fi
          git push --follow-tags
          echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Generate Release # create release page on github with `.vsix` file
        run: | # shell
          gh release create v$VERSION --generate-notes rascal-syntax-highlighter-$VERSION.vsix
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Release # upload to Extension Marketplace
        run: | # shell
          vsce publish --packagePath rascal-syntax-highlighter-$VERSION.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
